# Generated by Django 4.2.13 on 2024-06-09 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('software', models.TextField()),
                ('necessidadeDesc', models.TextField()),
                ('intervencaoDesc', models.TextField()),
                ('estado_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.estadoatendimento')),
                ('estado_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.estadoticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardwareTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.TextField()),
                ('avaria', models.TextField()),
                ('reparacaoDesc', models.TextField()),
                ('pecas', models.TextField()),
                ('estado_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.estadoatendimento')),
                ('estado_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TicketsApp.estadoticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
