# Generated by Django 4.2.13 on 2024-06-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareticket',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='softwareticket',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
