# Generated by Django 5.0.6 on 2024-06-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicketsApp', '0002_hardwareticket_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardwareticket',
            name='resolved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='softwareticket',
            name='resolved',
            field=models.BooleanField(null=True),
        ),
    ]
